"""made date a string

Revision ID: b12d5cd276c5
Revises: c4f4f9250173
Create Date: 2024-06-13 16:54:24.785033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12d5cd276c5'
down_revision = 'c4f4f9250173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('birthday',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
